### ISSUE TITLE
Error while running arm.xml

### ISSUE THREAD

**Issue by abhi-kumar** [robocomp/robocomp#26]
I get the following error while running arm.xml:

abhi@abhi-Inspiron-7520:~/robocomp/files/innermodel$ rcis arm.xml
---------------------------------------
--- FCL_SUPPORT: 0
---------------------------------------
Warning: STORM not found. RCISMousePicker topic will NOT be published 
InnerModelReader: reading arm.xml
InnerModelRGBD: 0.000000 {30000}
InnerModelRGBD: 0.000000 {30000}
Could not find /home/robocomp/robocomp/files/osgModels/data/cylinder.osg osg.
Segmentation fault (core dumped)

I searched for cylinder.osg in the entire source, but couldn't find it. I think we need to add this file.

**Comment by abhinavjain241** [comment]
Same error, also initially the file 'arm.xml' contained instances of '/home/robocomp/robocomp/Files/osgModels/piso_osg/suelo.osg' in the path to the file 'suelo.osg'. When we tried to run it, it couldn't find 'Could not find /home/robocomp/robocomp/Files/osgModels/piso_osg/suelo.osg osg' (Since Linux is case-sensitive) but then when we replace all instances of 'Files' to 'files', it runs giving the above specified error.
